### ISSUE TITLE
When audit went live this morning, started getting a lot of exceptions

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-audit-hook#39]
```
 at [Source: {"entity":"audit","data":[{"entityName":"entityJob","versionText":"1.0.0","lastUpdateDate":"20150428T10:57:08.538+0000","lastUpdatedBy":"censored","identity":[{"fieldText":"_id","valueText":"entityJob_136449"}],"audits":[{"fieldText":"jobExecutions.1.actualEndDate","newValue":"null"},{"fieldText":"jobExecutions.1.consistentDocumentCount","newValue":"0"},{"fieldText":"jobExecutions.0.hostName","newValue":"censored"},{"fieldText":"jobExecutions.1.pid","newValue":"censored"},{"fieldText":"configurationName","newValue":"censored"},{"fieldText":"jobExecutions.0.ownerName","newValue":"censored"},{"fieldText":"jobExecutions.1.overwrittenDocumentCount","newValue":"0"},{"fieldText":"lastUpdateDate","newValue":"20150402T13:45:08.000+0000"},{"fieldText":"jobExecutions.1.inconsistentDocumentCount","newValue":"0"},{"fieldText":"jobExecutions.0.sourceQuery","newValue":"null"},{"fieldText":"jobExecutions.0.actualStartDate","newValue":"20150428T10:56:54.146+0000"},{"fieldText":"jobExecutions#","newValue":"2"},{"fieldText":"creationDate","newValue":"20150402T13:45:08.000+0000"},{"fieldText":"createdBy","newValue":"someuser"},{"fieldText":"jobExecutions.0.actualEndDate","newValue":"null"},{"fieldText":"jobExecutions.1.jobStatus","newValue":"STARTING"},{"fieldText":"jobExecutions.1.processedDocumentCount","newValue":"0"},{"fieldText":"expectedExecutionMilliseconds","newValue":"30000"},{"fieldText":"objectType","newValue":"migrationJob"},{"fieldText":"lastUpdatedBy","newValue":"nmalik"},{"fieldText":"jobExecutions.0.pid","newValue":"16423@lightbluehystrix1.dev.a1.vary.redhat.com"},{"fieldText":"jobExecutions.0.overwrittenDocumentCount","newValue":"0"},{"fieldText":"jobExecutions.1.ownerName","newValue":"hystrix"},{"fieldText":"jobExecutions.1.hostName","newValue":"lightbluehystrix2.dev.a1.vary.redhat.com"},{"fieldText":"jobExecutions.0.inconsistentDocumentCount","newValue":"0"},{"fieldText":"endDate","newValue":"20100816T07:00:00.000+0000"},{"fieldText":"jobExecutions.0.consistentDocumentCount","newValue":"0"},{"fieldText":"_id","newValue":"entityJob_136449"},{"fieldText":"jobExecutions.1.sourceQuery","newValue":"null"},{"fieldText":"whenAvailableDate","newValue":"20100816T07:01:00.000+0000"},{"fieldText":"startDate","newValue":"20100816T06:00:00.000+0000"},{"fieldText":"jobExecutions.0.processedDocumentCount","newValue":"0"},{"fieldText":"jobExecutions.0.jobStatus","newValue":"RUNNING"},{"fieldText":"jobExecutions.1.actualStartDate","newValue":"20150428T10:57:06.593+0000"}]}]}; line: 1, column: 227]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1419)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:508)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:437)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipComma(ReaderBasedJsonParser.java:1795)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:608)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:212)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeArray(JsonNodeDeserializer.java:262)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:221)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:62)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:14)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3051)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:1818)
	at com.redhat.lightblue.util.JsonUtils.json(JsonUtils.java:66)
	at com.redhat.lightblue.hook.audit.AuditHook.processHook(AuditHook.java:202)
	at com.redhat.lightblue.hooks.HookManager.callQueuedHooks(HookManager.java:181)
	at com.redhat.lightblue.mediator.Mediator.update(Mediator.java:260)
	at com.redhat.lightblue.rest.crud.hystrix.UpdateCommand.run(UpdateCommand.java:65)
	at com.redhat.lightblue.rest.crud.hystrix.UpdateCommand.run(UpdateCommand.java:36)
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:294)
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:289)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable.unsafeSubscribe(Observable.java:7466)
	at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:514)
	at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:497)
	at rx.Observable.unsafeSubscribe(Observable.java:7466)
	at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by luan-cestari** [comment]
Hi @dcrissman I saw the part of the message and  I also dig the jackson code ( like the last line from stack trae https://github.com/FasterXML/jackson-core/blob/jackson-core-2.4.2/src/main/java/com/fasterxml/jackson/core/JsonParser.java#L1419 ) and I notice that the error is about an invalid character on the column 227, but looking at that exctaly position I don't see any invalid character and the whole JSON is valid. I was wondering if when you copy the message, if the clipboard or something removed the invalid character

**Comment by luan-cestari** [comment]
For this issue, I propose we change the current implementation of the creation of the  JSON in audit to use jackson

**Comment by dcrissman** [comment]
This still requires testing.

**Comment by dcrissman** [comment]
Closing on account that I am no longer seeing this exception.
